---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Install nginx
  become: true
  ansible.builtin.package:
    name:
    package: '{{ nginx__packages }}'
    state: present
  tags:
    - installation
