---
- name: Update apt cache
  become: true
  apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Install nginx
  become: true
  package:
    name:
      - 'nginx'
    state: "{{ nxinx__state }}"
