---
- name: Install nginx
  include_tasks: installation.yml

- name: Configure nginx
  include_tasks: nginx.yml

- name: Start nginx webserver
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - operation
    - nginx

- name: Configure nginx default site
  include_tasks: default_site.yml
  tags:
    - configuration
    - nginx
    - sites

- name: Configure nginx sites
  include_tasks: single_site.yml
  with_items: '{{ nginx_sites }}'
  loop_control:
    loop_var: site
  tags:
    - configuration
    - nginx
    - sites

# Restart nginx before doing acme stuff
- name: Flush handlers to restart nginx now
  meta: flush_handlers

- name: Configure acmetool and obtain certificates
  include_tasks: acme.yml
  tags:
    - configuration
    - acme
