---

- name: Restart nginx
  become: true
  ansible.builtin.systemd:
    name: 'nginx.service'
    daemon_reload: true
    state: restarted


- name: systemctl reload nginx
  become: true
  ansible.builtin.systemd:
    name: 'nginx.service'
    daemon_reload: true
    state: reloaded
